export const createOrder = async(req,res)=>{
    try {
        
        
    } catch (error) {
        return res.status(500).json({msg : "Internal server error"})
    }
}